name: Update README2

on:
  schedule:
    - cron: "0 */12 * * *" # Se ejecuta cada 12 horas
  workflow_dispatch: # Bot√≥n para ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4
      
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
      
